#ifndef CORE_APPLICATION_EVENTS__BINARY_FILE_LOADED_EVENT_HPP_
#define CORE_APPLICATION_EVENTS__BINARY_FILE_LOADED_EVENT_HPP_

#include <shared/message/IMessage.hpp>

class CBinaryFileLoadedEvent : public IMessage
{
};

#endif // CORE_APPLICATION_EVENTS__BINARY_FILE_LOADED_EVENT_HPP_
