#ifndef SRC_CORE_APPLICATION_EVENTS__DETECTED_UNSUPPORTED_FILE_EVENT_HPP_
#define SRC_CORE_APPLICATION_EVENTS__DETECTED_UNSUPPORTED_FILE_EVENT_HPP_





#include <shared/message/IMessage.hpp>

class DetectedUnsupportedFileEvent : public IMessage
{
};




#endif // SRC_CORE_APPLICATION_EVENTS__DETECTED_UNSUPPORTED_FILE_EVENT_HPP_
