set(CMAKE_SYSTEM_NAME Darwin)

set(CMAKE_C_COMPILER apple_x86_64_cc)
set(CMAKE_CXX_COMPILER apple_86_64_cxx)

set(CMAKE_FIND_ROOT_PATH apple_x86_64_env)

set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)

