#ifndef SRC_LOADER_APPLICATION_EVENTS__U_I_REQUESTED_OPEN_FILE_EVENT_HPP_
#define SRC_LOADER_APPLICATION_EVENTS__U_I_REQUESTED_OPEN_FILE_EVENT_HPP_





#include <shared/message/IMessage.hpp>

class CUIRequestedOpenFileEvent : public IMessage
{
};



#endif // SRC_LOADER_APPLICATION_EVENTS__U_I_REQUESTED_OPEN_FILE_EVENT_HPP_
